---
title: "Lesson Plan"
description: " "
date-modified: "last-modified"
format: html
editor: visual
---

| Lesson | Date | Venue | Topic | Remarks |
|---------------|:--------------|---------------|:--------------|:--------------|
| 1 | 18/1 | SOE/SCIS2 SR B5-2 | [Introduction to Visual Analytics](outline/Lesson01_outline.html) |  |
| 2 | 25/1 | SOE/SCIS2 SR B5-2 | [Designing Graphs to Enlighten](outline/Lesson02_outline.html) |  |
| 3 | 1/2 | SOE/SCIS2 SR B5-2 | [Interactivity in Visual Analytics](outline/Lesson03_outline.html) |  |
| 4 | 8/2 | SOE/SCIS2 SR B5-2 | [Fundamentals of Visual Analytics](outline/Lesson04_outline.html) |  |
| 5 | 15/2 | SOE/SCIS2 SR B5-2 | [Visual Multivariate Analysis](outline/Lesson05_outline.html) |  |
| 6 | 22/2 | SOE/SCIS2 SR B5-2 | [Designing Web-enabled Visual Analytics Application with Shiny]() |  |
| 7 | 1/3 | SOE/SCIS2 SR B5-2 | [Visualising and Analysing Time-Oriented Data](outline/Lesson07_outline.html) |  |
|  | 8/3 |  | Recess week |  |
| 8 | 15/3 | SOE/SCIS2 SR B5-2 | [Visualising and Analysing Geographic Data](outline/Lesson08_outline.html) |  |
| 9 | 22/3 | SOE/SCIS2 SR B5-2 | [Visualising and Analysing Network Data](outline/Lesson09_outline.html) |  |
| 10 | 29/3 | SOE/SCIS2 SR B5-2 | [Information Dashboard Design](outline/Lesson10_outline.html) |  |
| 11 | 5/4 | TBC | Poster Presentation |  |
