---
title: "Take-home Exercise 1"
date: "January 20, 2025"
date-modified: "last-modified"
format: html
editor: visual
---

::: {style="font-size: 200%;"}
***Creating data visualisation beyond default***
:::

## Overview

This handout provides the context, task, expectations and grading criteria of Take-home Exercise 1. Students must review and understand them before getting started with the take-home exercise.

## Setting the scene

An international media company that publishes weekly content on digital platforms is planning to release articles on the following themes.

- Heart Attack in Japan
- Ship Performance in the Gulf of Guinea

## The Task

Assuming the role of the graphical editor of the media company, you are tasked to choose one of the theme above and to prepare data visualisation for the article.

## The Data

To accomplish the task, one of the following data sets should be used:

- [Heart Attack in Japan Youth Vs Adult](https://www.kaggle.com/datasets/ashaychoudhary/heart-attack-in-japan-youth-vs-adult)
- [Ship Performance Clustering Dataset](https://www.kaggle.com/datasets/jeleeladekunlefijabi/ship-performance-clustering-dataset)

## The Designing Tool

The data should be processed by using appropriate **tidyverse** family of packages and the statistical graphics must be prepared using **ggplot2** and its extensions.

## The Write-up

The write-up of the take-home exercise should include but not limited to the followings:

-   A reproducible description of the procedures used to prepare the analytical visualisation. Please refer to the senior submission I shared below.

-   A write-up of not more than **150 words** per each data visualisation, describing and discussing the patterns and/or trends reveal by each visualisation prepared.

# Submission Instructions

This is an individual assignment. You are required to work on the take-home exercises and prepare submission individually.

::: callout-important
The specific submission instructions are as follows:

-   The analytical visualisation must be prepared by using **R and appropriate R packages**.
-   Limit your submission to not more than **ten** data visualisation, minimum **five**.
-   The write-up of the take-home exercise must be in **Quarto html document** format. You are required to publish the write-up on [**Netlify**](https://www.netlify.com/).
:::

## Submission date

Your completed take-home exercise is due on **16th February 2025 (Sunday) by 11:59pm mid-night**.

## Learning from senior

-   [KYLIE TAN JING YI](https://akalestale.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
-   [TOA ZI YING JANET](https://janettoaisss608.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
-   [LEW YING ZHEN SERENA](https://isss608-spacebun.netlify.app/take-home_ex/take-home_ex1/take-home_ex1)
-   [SENG JING YI](https://jingyi-vaa.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
-   [JAYA GEORGE](https://isss608-jayageorge.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)

## Peer Learning




